### ISSUE TITLE
JSON API validation

### ISSUE THREAD

**Issue by Thisisjuke** [wizardstechnologies/node-api-platform#1]
Hey, I added "type" in my JSON Mock and had the error : child "xyz" fails because ["myDatas" at position 0 fails because ["type is not allowed"]].

I had to modify the node package to add "type" to the validation. Maybe you can create a feature or something to add our own validator without modifying the package.
Huge waste of time to solve this..

**Comment by LouisHrg** [comment]
😢

**Comment by BigZ** [comment]
i will close this issue because it has been solved by this commit: https://github.com/wizardstechnologies/node-api-platform/commit/d731ac9351139d19154af629d1f84ac62dd8832e

Next time, you can get in touch with me directly i'd be quite fast to answer.
Oh, and also, you can provide your own validator to Joi. the one provided here is just to make it handy !

Cheers,
